openapi: 3.0.0
info:
  title: U-tasks repository API
  description: An API of u-tasks-repository service
  version: 1.0.0
paths:
  /api/v1/users:
    get:
      summary: List all users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Create a user
      requestBody:
        description: The user to create
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: User created
  /api/v1/users/{username}:
    get:
      summary: Get a user by username
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
  /api/v1/projects:
    get:
      summary: List all projects
      responses:
        '200':
          description: List of all awalible projects
          content:
            application/json:
              schema:
                type: array
                propertyes:
                  object:
                    properties:
                      objectid:
                        type: string
                      objectname:
                        type: string
